#!/bin/bash

error()
{
    echo $1
    exit 1
}

[[ $# -eq 1 ]] || error "Usage: zygote <your.project.package.name>"

package=$1
ifs_orig=$IFS
IFS='.'
for i in $package;
do
    ((len++))
    [[ $i =~ ^[_a-z][_0-9a-z]*$ ]] || error "illegal package name item: $i"
done

[[ $len -gt 1 ]] || error "package name must contain at least two elements"

app=${i^}
IFS=$ifs_orig

git clone --depth 1 -b zygote https://github.com/butoff/zygote.git $app
cd $app
rm -rf .git
cd app
sed -i "s/com\.example\.zygote/$package/g" build.gradle src/main/AndroidManifest.xml
sed -i "s/Zygote/$app/g" src/main/AndroidManifest.xml
cd ../..
