#!/bin/bash

error()
{
    echo $1
    exit 1
}

[[ $# -eq 1 ]] || error "Usage: zygote <your.project.package.name>"

package=$1
ifs_orig=$IFS
IFS='.'
for component in $package;
do
    ((len++))
    [[ $component =~ ^[_a-z][_0-9a-z]*$ ]] || error "illegal package name item: $component"
done
IFS=$ifs_orig

[[ $len -gt 1 ]] || error "package name must contain at least two elements"

app=${component^}
git clone --depth 1 -b zygote https://github.com/butoff/zygote.git $app
cd $app
rm -rf .git

sed -i "s/# zygote/# $app/g" README.md

cd app
sed -i "s/zygote/$package/g" build.gradle src/main/AndroidManifest.xml
sed -i "s/Zygote/$app/g" src/main/AndroidManifest.xml

cd src/main/java
sed -i "s/zygote/$package/g" zygote/MainActivity.java
mkdir -p ${package//./\/}
mv zygote/MainActivity.java ${package//./\/}
rmdir zygote

cd ../../../../..
